/** Lightweight sync map of tool ID → meta description (kept small for initial bundle) */
export const metaDescriptions: Record<string, string> = {
  "csv-to-parquet": "Convert CSV files to Apache Parquet format with Snappy or Zstd compression. Free, offline, runs in your browser with DuckDB-WASM.",
  "parquet-to-csv": "Export Apache Parquet files to CSV format. Free, offline browser tool powered by DuckDB-WASM. No uploads required.",
  "csv-to-json": "Convert CSV files to JSON Array or NDJSON format. Free, offline tool with pretty-print and download. No data leaves your browser.",
  "json-to-csv": "Convert JSON and NDJSON files to CSV format. Flatten nested objects into tabular data. Free, offline browser tool.",
  "json-to-parquet": "Convert JSON files to Parquet with Snappy or Zstd compression. Reduce file size by 50-90%. Free, offline browser tool.",
  "parquet-to-json": "Convert Parquet files to JSON Array or NDJSON. Preserves nested types. Free, offline browser tool powered by DuckDB-WASM.",
  "excel-to-csv": "Convert Excel (XLSX, XLS) files to CSV with multi-sheet export. Free, offline browser tool. No uploads.",
  "csv-to-excel": "Convert CSV files to Excel (XLSX) with multi-sheet support. Combine multiple CSVs into one workbook. Free, offline browser tool.",
  "excel-csv-converter": "Convert Excel (XLSX, XLS) to CSV and CSV to Excel. Multi-sheet support. Free, offline browser tool. No uploads.",
  "csv-viewer": "View CSV, TSV, and delimited files in a sortable, searchable table with column statistics. Auto-detect or set custom delimiters. Free, offline.",
  "parquet-viewer": "View Parquet file data, schema, and metadata in your browser. Export to CSV or JSON. Free, offline tool.",
  "json-formatter": "Format, minify, validate, and sort JSON with tree view. Free, offline JSON formatter in your browser.",
  "sql-playground": "Run SQL queries on local CSV, Parquet, JSON, and Excel files with full DuckDB syntax. JOINs, CTEs, window functions. Free, offline.",
  "data-profiler": "Profile datasets to discover nulls, duplicates, outliers, and data quality issues. Free, offline browser tool.",
  "json-flattener": "Flatten deeply nested JSON into tabular format. Configurable separators and array handling. Free, offline tool.",
  "schema-generator": "Generate CREATE TABLE DDL for PostgreSQL, MySQL, BigQuery, Snowflake from your data. Free, offline schema generator.",
  "csv-to-sql": "Generate CREATE TABLE and INSERT statements from CSV files. PostgreSQL, MySQL, SQLite, BigQuery dialects. Free, offline.",
  "dataset-diff": "Compare two dataset versions side-by-side. Identify added, removed, and modified rows. Free, offline diff tool.",
  "csv-inspector": "Inspect CSV file encoding, delimiter, line endings, column types, null patterns, and data quality. Free, offline, in your browser.",
  "json-inspector": "Inspect JSON file structure, schema consistency, value types, and nesting depth. Free, offline browser tool.",
  "parquet-inspector": "Inspect Parquet file metadata, row groups, column encodings, compression stats. Free, offline browser tool powered by DuckDB-WASM.",
  "data-sampler": "Extract random or stratified samples from large CSV, Parquet, or JSON files. Free, offline browser tool powered by DuckDB-WASM.",
  "deduplicator": "Find and remove duplicate rows from CSV, Parquet, or JSON files. Choose uniqueness columns and keep strategy. Free, offline browser tool.",
  "sql-formatter": "Format, beautify, and minify SQL with dialect-aware formatting for PostgreSQL, MySQL, BigQuery, SQLite. Free, offline browser tool.",
  "markdown-table": "Convert CSV, JSON, or Parquet files into formatted Markdown tables. Copy for GitHub, docs, and READMEs. Free, offline browser tool.",
  "column-editor": "Select, reorder, and rename columns in CSV, JSON, or Parquet files. Export cleaned data. Free, offline browser tool.",
  "data-merge": "Join two datasets with inner, left, right, full outer, or cross joins. Visual merge tool. Free, offline browser tool powered by DuckDB-WASM.",
  "pivot-table": "Build pivot tables from CSV, JSON, or Parquet files. Visual field mapping with sum, count, avg, min, max aggregation. Free, offline browser tool.",
  "chart-builder": "Create bar, line, area, pie, and scatter charts from CSV, JSON, or Parquet files. Export as PNG. Free, offline browser tool.",
  "yaml-to-json": "Convert YAML to JSON with validation and formatting options. Free, offline browser tool.",
  "json-to-yaml": "Convert JSON to YAML with formatting options. Free, offline browser tool.",
  "regex-filter": "Filter dataset rows using regex patterns on any column. Preview matches and download filtered data. Free, offline browser tool.",
  "xml-to-json": "Convert XML files to JSON with attribute handling options. Free, offline browser tool using DOMParser.",
  "json-to-xml": "Convert JSON files to XML with customizable root element and indentation. Free, offline browser tool.",
  "csv-splitter": "Split large CSV files by row count or column value into smaller files. Free, offline browser tool powered by DuckDB-WASM.",
  "base64": "Encode text or files to Base64 and decode Base64 back to text. Free, offline browser tool. No uploads.",
  "data-anonymizer": "Mask, redact, hash, or fake sensitive columns in CSV, JSON, or Parquet files. Free, offline data anonymizer.",
  "hash-generator": "Generate SHA-256, SHA-384, SHA-512 hashes from text or files. Free, offline browser tool using Web Crypto API.",
  "data-generator": "Generate realistic sample datasets with configurable columns, types, and row counts. Names, emails, dates, UUIDs. Free, offline.",
  "json-schema-validator": "Validate JSON documents against JSON Schema definitions. See errors with paths. Free, offline browser tool using Ajv.",
  "toml-to-json": "Convert TOML configuration files to JSON format. Free, offline browser tool with auto-conversion.",
  "json-to-toml": "Convert JSON documents to TOML configuration format. Free, offline browser tool.",
  "excel-viewer": "View Excel (XLSX, XLS) files in your browser with multi-sheet navigation. Sortable tables, no uploads, no installs.",
  "yaml-formatter": "Format, minify, and validate YAML documents in your browser. Pretty-print with configurable indentation. Free, offline.",
  "log-viewer": "View and filter log files with level detection, regex search, and line numbers. Free, offline browser tool.",
  "hex-viewer": "Inspect binary files with hex and ASCII columns. Navigate by offset, paginate large files. Free, offline browser tool.",
  "xml-formatter": "Format, minify, and validate XML documents in your browser. Pretty-print with configurable indentation. Free, offline.",
  "json-diff": "Compare two JSON documents side-by-side with inline diff highlighting. Free, offline browser tool. No data leaves your machine.",
  "url-encoder": "Encode and decode URLs and query strings. Handles special characters, Unicode, and percent-encoding. Free, offline browser tool.",
  "cron-parser": "Parse and explain cron expressions in plain English. See next run times and validate syntax. Free, offline browser tool.",
  "encoding-detector": "Detect file character encoding, BOM markers, and line endings. Identify UTF-8, ASCII, ISO-8859, and more. Free, offline browser tool.",
  "qr-code": "Generate QR codes from text, URLs, or any data. Customize size and error correction. Download as PNG. Free, offline browser tool.",
  "image-compressor": "Compress images with quality control. Output JPEG, PNG, or WebP. See file size reduction. Free, offline browser tool.",
  "password-generator": "Generate cryptographically secure passwords with customizable length and character rules. Free, offline browser tool.",
  "regex-tester": "Test regular expressions with real-time match highlighting and capture group display. Free, offline browser tool.",
  "color-picker": "Convert between Hex, RGB, and HSL color formats. Check WCAG contrast ratios. Free, offline browser tool.",
  "text-diff": "Compare two text blocks with line-by-line diff highlighting. See additions, deletions, and unchanged lines. Free, offline browser tool.",
  "uuid-generator": "Generate UUID v4 (random) and v7 (timestamp-based) identifiers. Bulk generation up to 100. Free, offline browser tool.",
  "timestamp-converter": "Convert between Unix epoch timestamps and human-readable dates. Supports seconds and milliseconds. Free, offline browser tool.",
  "jwt-decoder": "Decode JWT tokens to inspect header, payload, and claims. See expiration status. Free, offline browser tool — no data leaves your machine.",
  "svg-to-png": "Convert SVG files to PNG with custom scale (1×–8×) and transparent or colored backgrounds. Free, offline browser tool.",
  "favicon-generator": "Generate favicons in all standard sizes (16×16 to 512×512) from any image. Free, offline browser tool.",
  "css-formatter": "Format or minify CSS with proper indentation and structure. Free, offline browser tool.",
  "js-formatter": "Format or minify JavaScript code with customizable indentation. Free, offline browser tool.",
  "image-to-base64": "Convert images to Base64 data URIs for embedding in HTML and CSS. Free, offline browser tool.",
  "markdown-editor": "Write and preview Markdown with live rendering. Split, edit, and preview modes. Free, offline browser tool.",
  "meta-tag-generator": "Generate HTML meta tags for SEO, Open Graph, and Twitter Cards. Preview and copy. Free, offline browser tool.",
  "robots-txt-generator": "Generate robots.txt files with presets for AI crawlers, search engines, and custom rules. Free, offline browser tool.",
  "chmod-calculator": "Calculate Unix file permissions in octal and symbolic notation. Visual chmod calculator. Free, offline browser tool.",
  "json-to-typescript": "Generate TypeScript interfaces or type aliases from JSON data. Free, offline browser tool.",
  "lorem-ipsum": "Generate Lorem Ipsum placeholder text by paragraphs, sentences, or words. Free, offline browser tool.",
  "html-entity-encoder": "Encode and decode HTML entities, special characters, and Unicode. Reference table included. Free, offline browser tool.",
  "slug-generator": "Generate URL-friendly slugs from text with custom separators and length limits. Free, offline browser tool.",
  "word-counter": "Count words, characters, sentences, paragraphs, and estimate reading time. Free, offline browser tool.",
  "gitignore-generator": "Generate .gitignore files from templates for Node.js, Python, Go, Rust, Java, and more. Free, offline browser tool.",
  "sitemap-generator": "Build XML sitemaps with URLs, priorities, change frequencies, and last modified dates. Free, offline browser tool.",
};
